export const LEVELS = [
  {
    id: 0,
    title: 'Greetings',
    titleIndo: 'Salam',
    emoji: '👋',
    color: '#FF6B6B',
    bg: 'linear-gradient(135deg,#FF6B6B,#FF8E53)',
    words: [
      { indo: 'Halo', eng: 'Hello', emoji: '👋' },
      { indo: 'Selamat pagi', eng: 'Good morning', emoji: '🌅' },
      { indo: 'Selamat siang', eng: 'Good afternoon', emoji: '☀️' },
      { indo: 'Selamat malam', eng: 'Good evening', emoji: '🌙' },
      { indo: 'Apa kabar?', eng: 'How are you?', emoji: '🙂' },
      { indo: 'Baik, terima kasih', eng: 'Fine, thank you', emoji: '😊' },
      { indo: 'Sampai jumpa', eng: 'Goodbye', emoji: '👋' },
      { indo: 'Ya', eng: 'Yes', emoji: '✅' },
      { indo: 'Tidak', eng: 'No', emoji: '❌' },
      { indo: 'Tolong', eng: 'Please', emoji: '🙏' },
    ],
  },
  {
    id: 1,
    title: 'Numbers',
    titleIndo: 'Angka',
    emoji: '🔢',
    color: '#26C6A6',
    bg: 'linear-gradient(135deg,#26C6A6,#0694A2)',
    words: [
      { indo: 'Satu', eng: 'One', emoji: '1️⃣' },
      { indo: 'Dua', eng: 'Two', emoji: '2️⃣' },
      { indo: 'Tiga', eng: 'Three', emoji: '3️⃣' },
      { indo: 'Empat', eng: 'Four', emoji: '4️⃣' },
      { indo: 'Lima', eng: 'Five', emoji: '5️⃣' },
      { indo: 'Enam', eng: 'Six', emoji: '6️⃣' },
      { indo: 'Tujuh', eng: 'Seven', emoji: '7️⃣' },
      { indo: 'Delapan', eng: 'Eight', emoji: '8️⃣' },
      { indo: 'Sembilan', eng: 'Nine', emoji: '9️⃣' },
      { indo: 'Sepuluh', eng: 'Ten', emoji: '🔟' },
    ],
  },
  {
    id: 2,
    title: 'Family',
    titleIndo: 'Keluarga',
    emoji: '👨‍👩‍👧‍👦',
    color: '#A78BFA',
    bg: 'linear-gradient(135deg,#A78BFA,#7C3AED)',
    words: [
      { indo: 'Ibu', eng: 'Mother', emoji: '👩' },
      { indo: 'Ayah', eng: 'Father', emoji: '👨' },
      { indo: 'Kakak', eng: 'Older sibling', emoji: '🧑' },
      { indo: 'Adik', eng: 'Younger sibling', emoji: '👶' },
      { indo: 'Kakek', eng: 'Grandfather', emoji: '👴' },
      { indo: 'Nenek', eng: 'Grandmother', emoji: '👵' },
      { indo: 'Paman', eng: 'Uncle', emoji: '🧔' },
      { indo: 'Bibi', eng: 'Aunt', emoji: '👩‍🦱' },
      { indo: 'Sepupu', eng: 'Cousin', emoji: '🧑‍🤝‍🧑' },
      { indo: 'Anak', eng: 'Child', emoji: '🧒' },
    ],
  },
  {
    id: 3,
    title: 'Food',
    titleIndo: 'Makanan',
    emoji: '🍜',
    color: '#FB923C',
    bg: 'linear-gradient(135deg,#FB923C,#F59E0B)',
    words: [
      { indo: 'Nasi', eng: 'Rice', emoji: '🍚' },
      { indo: 'Mie', eng: 'Noodles', emoji: '🍜' },
      { indo: 'Ayam', eng: 'Chicken', emoji: '🍗' },
      { indo: 'Ikan', eng: 'Fish', emoji: '🐟' },
      { indo: 'Buah', eng: 'Fruit', emoji: '🍎' },
      { indo: 'Air', eng: 'Water', emoji: '💧' },
      { indo: 'Susu', eng: 'Milk', emoji: '🥛' },
      { indo: 'Roti', eng: 'Bread', emoji: '🍞' },
      { indo: 'Telur', eng: 'Egg', emoji: '🥚' },
      { indo: 'Sayur', eng: 'Vegetables', emoji: '🥦' },
    ],
  },
  {
    id: 4,
    title: 'Animals',
    titleIndo: 'Hewan',
    emoji: '🐘',
    color: '#60A5FA',
    bg: 'linear-gradient(135deg,#60A5FA,#3B82F6)',
    words: [
      { indo: 'Kucing', eng: 'Cat', emoji: '🐱' },
      { indo: 'Anjing', eng: 'Dog', emoji: '🐶' },
      { indo: 'Gajah', eng: 'Elephant', emoji: '🐘' },
      { indo: 'Harimau', eng: 'Tiger', emoji: '🐯' },
      { indo: 'Monyet', eng: 'Monkey', emoji: '🐒' },
      { indo: 'Burung', eng: 'Bird', emoji: '🐦' },
      { indo: 'Ular', eng: 'Snake', emoji: '🐍' },
      { indo: 'Kuda', eng: 'Horse', emoji: '🐴' },
      { indo: 'Sapi', eng: 'Cow', emoji: '🐄' },
      { indo: 'Kelinci', eng: 'Rabbit', emoji: '🐰' },
    ],
  },
]

export const TASKS = [
  {
    id: 'flashcard',
    name: 'Flashcards',
    icon: '🃏',
    iconBg: '#FFE0E8',
    desc: 'Learn the words with picture cards',
  },
  {
    id: 'match',
    name: 'Match Game',
    icon: '🔗',
    iconBg: '#CCFBF1',
    desc: 'Match Indonesian words to English',
  },
  {
    id: 'quiz',
    name: 'Quiz Time!',
    icon: '⭐',
    iconBg: '#FEF3C7',
    desc: 'Answer questions to earn stars',
  },
]
