export const LEVELS = [
  {
    id: 0,
    title: 'Greetings',
    titleIndo: 'Salam',
    emoji: '👋',
    color: '#FF6B6B',
    bg: 'linear-gradient(135deg,#FF6B6B,#FF8E53)',
    tip: 'In Indonesia, people say Halo! just like Hello!',
    words: [
      { indo: 'Halo', eng: 'Hello', emoji: '👋', pronunciation: 'Hah-loh' },
      { indo: 'Ya', eng: 'Yes', emoji: '✅', pronunciation: 'Yah' },
      { indo: 'Tidak', eng: 'No', emoji: '❌', pronunciation: 'Tee-dahk' },
      { indo: 'Tolong', eng: 'Please', emoji: '🙏', pronunciation: 'Toh-long' },
      { indo: 'Terima kasih', eng: 'Thank you', emoji: '😊', pronunciation: 'Teh-ree-mah kah-see' },
      { indo: 'Selamat pagi', eng: 'Good morning', emoji: '🌅', pronunciation: 'Seh-lah-maht pah-gee' },
    ],
  },
  {
    id: 1,
    title: 'Numbers',
    titleIndo: 'Angka',
    emoji: '🔢',
    color: '#26C6A6',
    bg: 'linear-gradient(135deg,#26C6A6,#0694A2)',
    tip: 'Indonesian numbers are easy to say — sound them out!',
    words: [
      { indo: 'Satu', eng: 'One', emoji: '1️⃣', pronunciation: 'Sah-too' },
      { indo: 'Dua', eng: 'Two', emoji: '2️⃣', pronunciation: 'Doo-ah' },
      { indo: 'Tiga', eng: 'Three', emoji: '3️⃣', pronunciation: 'Tee-gah' },
      { indo: 'Empat', eng: 'Four', emoji: '4️⃣', pronunciation: 'Em-paht' },
      { indo: 'Lima', eng: 'Five', emoji: '5️⃣', pronunciation: 'Lee-mah' },
      { indo: 'Enam', eng: 'Six', emoji: '6️⃣', pronunciation: 'En-ahm' },
    ],
  },
  {
    id: 2,
    title: 'Family',
    titleIndo: 'Keluarga',
    emoji: '👨‍👩‍👧‍👦',
    color: '#A78BFA',
    bg: 'linear-gradient(135deg,#A78BFA,#7C3AED)',
    tip: 'Indonesians love family — keluarga means family!',
    words: [
      { indo: 'Ibu', eng: 'Mum', emoji: '👩', pronunciation: 'Ee-boo' },
      { indo: 'Ayah', eng: 'Dad', emoji: '👨', pronunciation: 'Ah-yah' },
      { indo: 'Kakak', eng: 'Big brother or sister', emoji: '🧑', pronunciation: 'Kah-kahk' },
      { indo: 'Adik', eng: 'Little brother or sister', emoji: '👶', pronunciation: 'Ah-deek' },
      { indo: 'Kakek', eng: 'Grandpa', emoji: '👴', pronunciation: 'Kah-kek' },
      { indo: 'Nenek', eng: 'Grandma', emoji: '👵', pronunciation: 'Neh-nek' },
    ],
  },
  {
    id: 3,
    title: 'Food',
    titleIndo: 'Makanan',
    emoji: '🍜',
    color: '#FB923C',
    bg: 'linear-gradient(135deg,#FB923C,#F59E0B)',
    tip: "Nasi goreng (fried rice) is Indonesia's most famous food!",
    words: [
      { indo: 'Nasi', eng: 'Rice', emoji: '🍚', pronunciation: 'Nah-see' },
      { indo: 'Mie', eng: 'Noodles', emoji: '🍜', pronunciation: 'Mee-eh' },
      { indo: 'Ayam', eng: 'Chicken', emoji: '🍗', pronunciation: 'Ah-yahm' },
      { indo: 'Air', eng: 'Water', emoji: '💧', pronunciation: 'Ah-eer' },
      { indo: 'Buah', eng: 'Fruit', emoji: '🍎', pronunciation: 'Boo-ah' },
      { indo: 'Telur', eng: 'Egg', emoji: '🥚', pronunciation: 'Teh-loor' },
    ],
  },
  {
    id: 4,
    title: 'Animals',
    titleIndo: 'Hewan',
    emoji: '🐘',
    color: '#60A5FA',
    bg: 'linear-gradient(135deg,#60A5FA,#3B82F6)',
    tip: 'Indonesia is home to tigers, elephants and orangutans!',
    words: [
      { indo: 'Kucing', eng: 'Cat', emoji: '🐱', pronunciation: 'Koo-ching' },
      { indo: 'Anjing', eng: 'Dog', emoji: '🐶', pronunciation: 'Ahn-jing' },
      { indo: 'Gajah', eng: 'Elephant', emoji: '🐘', pronunciation: 'Gah-jah' },
      { indo: 'Harimau', eng: 'Tiger', emoji: '🐯', pronunciation: 'Hah-ree-mow' },
      { indo: 'Monyet', eng: 'Monkey', emoji: '🐒', pronunciation: 'Moh-nyet' },
      { indo: 'Burung', eng: 'Bird', emoji: '🐦', pronunciation: 'Boo-roong' },
    ],
  },
]

export const TASKS = [
  {
    id: 'lesson',
    name: 'Learn It!',
    icon: '📖',
    iconBg: '#E0E7FF',
    desc: 'See and hear each word',
  },
  {
    id: 'sayit',
    name: 'Say It!',
    icon: '🔊',
    iconBg: '#FCE7F3',
    desc: 'Listen and choose the right word',
  },
  {
    id: 'match',
    name: 'Match It!',
    icon: '🔗',
    iconBg: '#CCFBF1',
    desc: 'Match Indonesian to English',
  },
  {
    id: 'quiz',
    name: 'Quiz Time!',
    icon: '⭐',
    iconBg: '#FEF3C7',
    desc: 'Answer questions to earn stars',
  },
]
