export const LEVELS = [
  {
    id: 0,
    title: 'Greetings',
    titleIndo: 'Salam',
    emoji: '👋',
    color: '#FF6B6B',
    bg: 'linear-gradient(135deg,#FF6B6B,#FF8E53)',
    tip: 'Indonesians are very friendly — always say Halo when you meet someone!',
    words: [
      { indo: 'Halo', eng: 'Hello', emoji: '👋', pronunciation: 'Hah-loh' },
      { indo: 'Ya', eng: 'Yes', emoji: '✅', pronunciation: 'Yah' },
      { indo: 'Tidak', eng: 'No', emoji: '❌', pronunciation: 'Tee-dahk' },
      { indo: 'Tolong', eng: 'Please', emoji: '🙏', pronunciation: 'Toh-long' },
      { indo: 'Terima kasih', eng: 'Thank you', emoji: '😊', pronunciation: 'Teh-ree-mah kah-see' },
      { indo: 'Selamat pagi', eng: 'Good morning', emoji: '🌅', pronunciation: 'Seh-lah-maht pah-gee' },
    ],
    sentences: [
      { english: 'Hello, good morning!', words: ['Halo,', 'selamat', 'pagi!'] },
      { english: 'Yes, thank you!', words: ['Ya,', 'terima', 'kasih!'] },
      { english: 'No, please!', words: ['Tidak,', 'tolong!'] },
    ],
  },
  {
    id: 1,
    title: 'Numbers',
    titleIndo: 'Angka',
    emoji: '🔢',
    color: '#26C6A6',
    bg: 'linear-gradient(135deg,#26C6A6,#0694A2)',
    tip: 'Indonesian numbers are fun to say — they almost sound like music!',
    words: [
      { indo: 'Satu', eng: 'One', emoji: '1️⃣', pronunciation: 'Sah-too' },
      { indo: 'Dua', eng: 'Two', emoji: '2️⃣', pronunciation: 'Doo-ah' },
      { indo: 'Tiga', eng: 'Three', emoji: '3️⃣', pronunciation: 'Tee-gah' },
      { indo: 'Empat', eng: 'Four', emoji: '4️⃣', pronunciation: 'Em-paht' },
      { indo: 'Lima', eng: 'Five', emoji: '5️⃣', pronunciation: 'Lee-mah' },
      { indo: 'Enam', eng: 'Six', emoji: '6️⃣', pronunciation: 'En-ahm' },
      { indo: 'Tujuh', eng: 'Seven', emoji: '7️⃣', pronunciation: 'Too-jooh' },
      { indo: 'Delapan', eng: 'Eight', emoji: '8️⃣', pronunciation: 'Deh-lah-pahn' },
      { indo: 'Sembilan', eng: 'Nine', emoji: '9️⃣', pronunciation: 'Sem-bee-lahn' },
      { indo: 'Sepuluh', eng: 'Ten', emoji: '🔟', pronunciation: 'Seh-poo-looh' },
    ],
    sentences: [
      { english: 'One, two, three!', words: ['Satu,', 'dua,', 'tiga!'] },
      { english: 'Four, five, six!', words: ['Empat,', 'lima,', 'enam!'] },
      { english: 'Seven, eight, nine, ten!', words: ['Tujuh,', 'delapan,', 'sembilan,', 'sepuluh!'] },
    ],
  },
  {
    id: 2,
    title: 'About Me',
    titleIndo: 'Tentang Aku',
    emoji: '🙋',
    color: '#F472B6',
    bg: 'linear-gradient(135deg,#F472B6,#EC4899)',
    tip: 'Indonesians love to introduce themselves — "Nama saya" means "My name is"!',
    words: [
      { indo: 'Nama saya', eng: 'My name is', emoji: '🏷️', pronunciation: 'Nah-mah sah-yah' },
      { indo: 'Saya', eng: 'I am / I', emoji: '👤', pronunciation: 'Sah-yah' },
      { indo: 'Berumur', eng: 'Years old', emoji: '🎂', pronunciation: 'Beh-roo-moor' },
      { indo: 'Dari', eng: 'From', emoji: '🌏', pronunciation: 'Dah-ree' },
      { indo: 'Suka', eng: 'Like', emoji: '❤️', pronunciation: 'Soo-kah' },
      { indo: 'Tidak suka', eng: 'Don\'t like', emoji: '👎', pronunciation: 'Tee-dahk soo-kah' },
      { indo: 'Lapar', eng: 'Hungry', emoji: '🍽️', pronunciation: 'Lah-pahr' },
      { indo: 'Senang', eng: 'Happy', emoji: '😄', pronunciation: 'Seh-nahng' },
    ],
    sentences: [
      { english: 'My name is ...', words: ['Nama', 'saya', '...'] },
      { english: 'I am happy!', words: ['Saya', 'senang!'] },
      { english: 'I am hungry.', words: ['Saya', 'lapar.'] },
      { english: 'I like ...', words: ['Saya', 'suka', '...'] },
    ],
  },
  {
    id: 3,
    title: 'Colours',
    titleIndo: 'Warna',
    emoji: '🎨',
    color: '#8B5CF6',
    bg: 'linear-gradient(135deg,#8B5CF6,#6D28D9)',
    tip: 'The Indonesian flag is merah (red) and putih (white)!',
    words: [
      { indo: 'Merah', eng: 'Red', emoji: '🔴', pronunciation: 'Meh-rah' },
      { indo: 'Biru', eng: 'Blue', emoji: '🔵', pronunciation: 'Bee-roo' },
      { indo: 'Kuning', eng: 'Yellow', emoji: '🟡', pronunciation: 'Koo-ning' },
      { indo: 'Hijau', eng: 'Green', emoji: '🟢', pronunciation: 'Hee-jow' },
      { indo: 'Putih', eng: 'White', emoji: '⚪', pronunciation: 'Poo-tee' },
      { indo: 'Hitam', eng: 'Black', emoji: '⚫', pronunciation: 'Hee-tahm' },
      { indo: 'Oranye', eng: 'Orange', emoji: '🟠', pronunciation: 'Oh-rahn-yeh' },
      { indo: 'Merah muda', eng: 'Pink', emoji: '🩷', pronunciation: 'Meh-rah moo-dah' },
    ],
    sentences: [
      { english: 'I like blue!', words: ['Saya', 'suka', 'biru!'] },
      { english: 'Red and white!', words: ['Merah', 'dan', 'putih!'] },
      { english: 'I like green and yellow.', words: ['Saya', 'suka', 'hijau', 'dan', 'kuning.'] },
    ],
  },
  {
    id: 4,
    title: 'Family',
    titleIndo: 'Keluarga',
    emoji: '👨‍👩‍👧‍👦',
    color: '#A78BFA',
    bg: 'linear-gradient(135deg,#A78BFA,#7C3AED)',
    tip: 'Family is very important in Indonesia — keluarga means family!',
    words: [
      { indo: 'Ibu', eng: 'Mum', emoji: '👩', pronunciation: 'Ee-boo' },
      { indo: 'Ayah', eng: 'Dad', emoji: '👨', pronunciation: 'Ah-yah' },
      { indo: 'Kakak', eng: 'Older sibling', emoji: '🧑', pronunciation: 'Kah-kahk' },
      { indo: 'Adik', eng: 'Younger sibling', emoji: '👶', pronunciation: 'Ah-deek' },
      { indo: 'Kakek', eng: 'Grandpa', emoji: '👴', pronunciation: 'Kah-kek' },
      { indo: 'Nenek', eng: 'Grandma', emoji: '👵', pronunciation: 'Neh-nek' },
      { indo: 'Paman', eng: 'Uncle', emoji: '🧔', pronunciation: 'Pah-mahn' },
      { indo: 'Bibi', eng: 'Aunt', emoji: '👩‍🦱', pronunciation: 'Bee-bee' },
    ],
    sentences: [
      { english: 'I like Mum and Dad.', words: ['Saya', 'suka', 'Ibu', 'dan', 'Ayah.'] },
      { english: 'My name is Grandma.', words: ['Nama', 'saya', 'Nenek.'] },
      { english: 'I have an older sibling.', words: ['Saya', 'punya', 'kakak.'] },
    ],
  },
  {
    id: 5,
    title: 'Classroom',
    titleIndo: 'Kelas',
    emoji: '🏫',
    color: '#F59E0B',
    bg: 'linear-gradient(135deg,#F59E0B,#D97706)',
    tip: 'In Indonesian schools, students say "Selamat pagi, Bu Guru" to greet their teacher!',
    words: [
      { indo: 'Buku', eng: 'Book', emoji: '📚', pronunciation: 'Boo-koo' },
      { indo: 'Pensil', eng: 'Pencil', emoji: '✏️', pronunciation: 'Pen-seel' },
      { indo: 'Meja', eng: 'Table', emoji: '🪑', pronunciation: 'Meh-jah' },
      { indo: 'Kursi', eng: 'Chair', emoji: '🪑', pronunciation: 'Koor-see' },
      { indo: 'Guru', eng: 'Teacher', emoji: '👩‍🏫', pronunciation: 'Goo-roo' },
      { indo: 'Murid', eng: 'Student', emoji: '🧑‍🎓', pronunciation: 'Moo-reed' },
      { indo: 'Papan tulis', eng: 'Whiteboard', emoji: '📋', pronunciation: 'Pah-bahn too-lees' },
      { indo: 'Tas', eng: 'Bag', emoji: '🎒', pronunciation: 'Tahs' },
    ],
    sentences: [
      { english: 'I have a book and a pencil.', words: ['Saya', 'punya', 'buku', 'dan', 'pensil.'] },
      { english: 'Good morning, teacher!', words: ['Selamat', 'pagi,', 'Guru!'] },
      { english: 'I am a student.', words: ['Saya', 'murid.'] },
    ],
  },
  {
    id: 6,
    title: 'Around the House',
    titleIndo: 'Rumah',
    emoji: '🏠',
    color: '#10B981',
    bg: 'linear-gradient(135deg,#10B981,#059669)',
    tip: 'Rumah means house — most Indonesian homes have a big front porch called a beranda!',
    words: [
      { indo: 'Rumah', eng: 'House', emoji: '🏠', pronunciation: 'Roo-mah' },
      { indo: 'Dapur', eng: 'Kitchen', emoji: '🍳', pronunciation: 'Dah-poor' },
      { indo: 'Kamar tidur', eng: 'Bedroom', emoji: '🛏️', pronunciation: 'Kah-mahr tee-door' },
      { indo: 'Kamar mandi', eng: 'Bathroom', emoji: '🚿', pronunciation: 'Kah-mahr mahn-dee' },
      { indo: 'Pintu', eng: 'Door', emoji: '🚪', pronunciation: 'Peen-too' },
      { indo: 'Jendela', eng: 'Window', emoji: '🪟', pronunciation: 'Jen-deh-lah' },
      { indo: 'Kursi', eng: 'Chair', emoji: '🪑', pronunciation: 'Koor-see' },
      { indo: 'Taman', eng: 'Garden', emoji: '🌿', pronunciation: 'Tah-mahn' },
    ],
    sentences: [
      { english: 'This is my house.', words: ['Ini', 'rumah', 'saya.'] },
      { english: 'The kitchen is big.', words: ['Dapur', 'besar.'] },
      { english: 'I like the garden.', words: ['Saya', 'suka', 'taman.'] },
    ],
  },
  {
    id: 7,
    title: 'Food & Drink',
    titleIndo: 'Makanan',
    emoji: '🍜',
    color: '#FB923C',
    bg: 'linear-gradient(135deg,#FB923C,#F59E0B)',
    tip: 'Nasi goreng (fried rice) is Indonesia\'s most famous dish — try saying it!',
    words: [
      { indo: 'Nasi', eng: 'Rice', emoji: '🍚', pronunciation: 'Nah-see' },
      { indo: 'Mie', eng: 'Noodles', emoji: '🍜', pronunciation: 'Mee-eh' },
      { indo: 'Ayam', eng: 'Chicken', emoji: '🍗', pronunciation: 'Ah-yahm' },
      { indo: 'Air', eng: 'Water', emoji: '💧', pronunciation: 'Ah-eer' },
      { indo: 'Susu', eng: 'Milk', emoji: '🥛', pronunciation: 'Soo-soo' },
      { indo: 'Buah', eng: 'Fruit', emoji: '🍎', pronunciation: 'Boo-ah' },
      { indo: 'Roti', eng: 'Bread', emoji: '🍞', pronunciation: 'Roh-tee' },
      { indo: 'Telur', eng: 'Egg', emoji: '🥚', pronunciation: 'Teh-loor' },
    ],
    sentences: [
      { english: 'I like rice and chicken.', words: ['Saya', 'suka', 'nasi', 'dan', 'ayam.'] },
      { english: 'I want water please.', words: ['Saya', 'mau', 'air,', 'tolong.'] },
      { english: 'I am hungry!', words: ['Saya', 'lapar!'] },
    ],
  },
  {
    id: 8,
    title: 'Animals',
    titleIndo: 'Hewan',
    emoji: '🐘',
    color: '#60A5FA',
    bg: 'linear-gradient(135deg,#60A5FA,#3B82F6)',
    tip: 'Indonesia is home to the Komodo dragon — the largest lizard on Earth!',
    words: [
      { indo: 'Kucing', eng: 'Cat', emoji: '🐱', pronunciation: 'Koo-ching' },
      { indo: 'Anjing', eng: 'Dog', emoji: '🐶', pronunciation: 'Ahn-jing' },
      { indo: 'Gajah', eng: 'Elephant', emoji: '🐘', pronunciation: 'Gah-jah' },
      { indo: 'Harimau', eng: 'Tiger', emoji: '🐯', pronunciation: 'Hah-ree-mow' },
      { indo: 'Monyet', eng: 'Monkey', emoji: '🐒', pronunciation: 'Moh-nyet' },
      { indo: 'Burung', eng: 'Bird', emoji: '🐦', pronunciation: 'Boo-roong' },
      { indo: 'Ikan', eng: 'Fish', emoji: '🐟', pronunciation: 'Ee-kahn' },
      { indo: 'Kelinci', eng: 'Rabbit', emoji: '🐰', pronunciation: 'Keh-lin-chee' },
    ],
    sentences: [
      { english: 'I like cats and dogs.', words: ['Saya', 'suka', 'kucing', 'dan', 'anjing.'] },
      { english: 'The elephant is big!', words: ['Gajah', 'besar!'] },
      { english: 'I don\'t like snakes.', words: ['Saya', 'tidak', 'suka', 'ular.'] },
    ],
  },
  {
    id: 9,
    title: 'My First Sentences',
    titleIndo: 'Kalimat Pertama',
    emoji: '💬',
    color: '#EF4444',
    bg: 'linear-gradient(135deg,#EF4444,#DC2626)',
    tip: 'You\'ve learned so much — now put it all together and speak Indonesian!',
    words: [
      { indo: 'Nama saya ...', eng: 'My name is ...', emoji: '🏷️', pronunciation: 'Nah-mah sah-yah' },
      { indo: 'Saya dari Australia', eng: 'I am from Australia', emoji: '🌏', pronunciation: 'Sah-yah dah-ree Aus-trah-lee-ah' },
      { indo: 'Saya berumur ... tahun', eng: 'I am ... years old', emoji: '🎂', pronunciation: 'Sah-yah beh-roo-moor ... tah-hoon' },
      { indo: 'Saya suka ...', eng: 'I like ...', emoji: '❤️', pronunciation: 'Sah-yah soo-kah' },
      { indo: 'Saya tidak suka ...', eng: 'I don\'t like ...', emoji: '👎', pronunciation: 'Sah-yah tee-dahk soo-kah' },
      { indo: 'Apa kabar?', eng: 'How are you?', emoji: '🙂', pronunciation: 'Ah-pah kah-bahr' },
      { indo: 'Baik, terima kasih!', eng: 'Good, thank you!', emoji: '😊', pronunciation: 'Bah-eek, teh-ree-mah kah-see' },
      { indo: 'Sampai jumpa!', eng: 'See you later!', emoji: '👋', pronunciation: 'Sahm-pie joom-pah' },
    ],
    sentences: [
      { english: 'My name is ... and I am from Australia.', words: ['Nama', 'saya', '...', 'dan', 'saya', 'dari', 'Australia.'] },
      { english: 'How are you? Good, thank you!', words: ['Apa', 'kabar?', 'Baik,', 'terima', 'kasih!'] },
      { english: 'I like cats. I don\'t like snakes.', words: ['Saya', 'suka', 'kucing.', 'Saya', 'tidak', 'suka', 'ular.'] },
      { english: 'See you later!', words: ['Sampai', 'jumpa!'] },
    ],
  },
]

export const TASKS = [
  {
    id: 'lesson',
    name: 'Learn It!',
    icon: '📖',
    iconBg: '#E0E7FF',
    desc: 'See and hear each word',
  },
  {
    id: 'sayit',
    name: 'Say It!',
    icon: '🔊',
    iconBg: '#FCE7F3',
    desc: 'Listen and choose the right word',
  },
  {
    id: 'match',
    name: 'Match It!',
    icon: '🔗',
    iconBg: '#CCFBF1',
    desc: 'Match Indonesian to English',
  },
  {
    id: 'quiz',
    name: 'Quiz Time!',
    icon: '⭐',
    iconBg: '#FEF3C7',
    desc: 'Answer questions to earn stars',
  },
  {
    id: 'build',
    name: 'Build It!',
    icon: '🧩',
    iconBg: '#FFE4E6',
    desc: 'Put the sentence together',
  },
]
